---

- name:   Update and upgrade apt packages
  become: true
  apt:
    upgrade:          yes
    update_cache:     yes
    cache_valid_time: 86400 #One day

- name: Install docker
  snap:
    name: "{{ item }}"
    state: present
  with_items:
    - 'docker'

- name: Install dependencies
  apt:
    pkg:
      - docker-compose
      - mysql-client
      - openjdk-8-jre
      - maven
    state: present