apiVersion: apps/v1
kind: Deployment
metadata:
  name: read_backend_deploy
  labels:
    app: help_queue_read
spec:
  replicas: 3
  selector:
    matchLabels:
      app: help_queue_read

  template:
    metadata:
      labels:
        app: help_queue_read
    spec:
      containers:
      - name: readticket
        image: jenkinsspicelatte/hq-backend-readticket
        ports:
        - containerPort: 5002