apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete_backend_deploy
  labels:
    app: help_queue_delete
spec:
  replicas: 3
  selector:
    matchLabels:
      app: help_queue_delete

  template:
    metadata:
      labels:
        app: help_queue_delete
    spec:
      containers:
      - name: deleteticket
        image: jenkinsspicelatte/hq-backend-deleteticket
        ports:
        - containerPort: 5004
        env:
        - name: DATABASE_URI
          value: -----ENVIRONMENT VARIABLE -----------
        - name: SECRET_KEY
          value: -----ENVIRONMENT VARIALBE -----------