apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete
  labels:
    app: delete
spec:
  replicas: 3
  selector:
    matchLabels:
      app: delete

  template:
    metadata:
      labels:
        app: delete
    spec:
      containers:
      - name: deleteticket-cont
        image: manishreddy1/hq-backend-deleteticket:latest
        ports:
        - containerPort: 8904
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ticketkey
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
---
apiVersion: v1
kind: Service
metadata:
  name: delete-ip
  labels:
    app : delete-ip
spec:
  selector:
    app: delete
  ports: 
  - protocol: TCP
    port: 8904
    targetPort: 8904
    nodePort: 8904
  type: ClusterIP