apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-backend-deploy
  labels:
    app: help-queue-read
spec:
  replicas: 3
  selector:
    matchLabels:
      app: help-queue-read

  template:
    metadata:
      labels:
        app: help-queue-read
    spec:
      containers:
      - name: readticket
        image: jenkinsspicelatte/hq-backend-readticket:latest
        ports:
        - containerPort: 5002
        imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2