apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-backend-deploy
  labels:
    app: help-queue-delete
spec:
  replicas: 3
  selector:
    matchLabels:
      app: help-queue-delete

  template:
    metadata:
      labels:
        app: help-queue-delete
    spec:
      containers:
      - name: deleteticket
        image: jenkinsspicelatte/hq-backend-deleteticket:latest
        ports:
        - containerPort: 5004
      imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2