apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-backend-deploy
  labels:
    app: help-queue-create-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: help-queue-create-backend

  template:
    metadata:
      labels:
        app: help-queue-create-backend
    spec:
      containers:
      - name: createticket
        image: jenkinsspicelatte/hq-backend-createticket:1.0.5PROD
        ports:
        - containerPort: 5001