apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-backend-deploy
  labels:
    app: help-queue-update
spec:
  replicas: 3
  selector:
    matchLabels:
      app: help-queue-update

  template:
    metadata:
      labels:
        app: help-queue-update
    spec:
      containers:
      - name: updateticket
        image: manishreddy1/hq-backend-updateticket:latest
        ports:
        - containerPort: 5003
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ticketkey
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2