apiVersion: apps/v1
kind: Deployment
metadata:
  name: create_backend
  labels:
    app: help_queue_create_backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: help_queue_create_backend

  template:
    metadata:
      labels:
        app: help_queue_create_backend
    spec:
      containers:
      - name: createticket
        image: jenkinsspicelatte/hq-backend-createticket:latest
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URI
          value: -----ENVIRONMENT VARIABLE -----------
        - name: SECRET_KEY
          value: -----ENVIRONMENT VARIALBE -----------