apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-backend-deploy
  labels:
    app: help-queue-create-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: help-queue-create-backend

  template:
    metadata:
      labels:
        app: help-queue-create-backend
    spec:
      containers:
      - name: createticket
        image: manishreddy1/hq-backend-createticket:latest
        ports:
        - containerPort: 5001
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ticketkey
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2

      