apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-backend
  labels:
    app: help-queue-create
spec:
  replicas: 3
  selector:
    matchLabels:
      app: help-queue-create

  template:
    metadata:
      labels:
        app: help-queue-create
    spec:
      containers:
      - name: createticket
        image: manishreddy1/hq-backend-createticket:latest
        ports:
        - containerPort: 5001
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ticketkey
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2

      