apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        location / {
            proxy_pass http://frontend:3000;
        }

        location /api/createTicket {
            proxy_pass http://backend:8901;
        }
        location /api/readTicket {
            proxy_pass http://backend:8902;
        }
        location /api/updateTicket {
            proxy_pass http://backend:8903;
        }
        location /api/deleteTicket {
            proxy_pass http://backend:8904;
        }
    }