apiVersion: v1
kind: Pod
metadata:
  name: svc_update_backend
  labels:
    app: svc_update_backend
spec:
  containers:
  - name: updateticket
    image: jenkinsspicelatte/hq-backend-updateticket:latest
    ports:
    - containerPort: 5003

apiVersion: v1
kind: Service
metadata:
  name: svc_update_backend
  labels:
    app : svc_update_backend
spec:
  selector:
    app: svc_update_backend
  ports: 
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: ClusterIP