apiVersion: v1
kind: Pod
metadata:
  name: svc_delete_backend
  labels:
    app: svc_help_queue_delete_backend
spec:
  containers:
  - name: deleteticket
    image: jenkinsspicelatte/hq-backend-deleteticket:latest
    ports:
    - containerPort: 5002

apiVersion: v1
kind: Service
metadata:
  name: svc_delete_backend
  labels:
    app : svc_delete_backend
spec:
  selector:
    app: svc_delete_backend
  ports: 
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP