apiVersion: v1
kind: Pod
metadata:
  name: svc_read_backend
  labels:
    app: svc_read_backend
spec:
  containers:
  - name: readticket
    image: jenkinsspicelatte/hq-backend-readticket:latest
    ports:
    - containerPort: 5002

apiVersion: v1
kind: Service
metadata:
  name: svc_read_backend
  labels:
    app : svc_read_backend
spec:
  selector:
    app: svc_read_backend
  ports: 
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP