---
- hosts: jenkins
  become: yes
  roles:
    - common
    - jenkins

- hosts: bastion
  become: yes
  roles:
    - common
    - bastion

- hosts: testvm
  become: yes
  roles:
    - common
    - testvm