---
- name: ReadJsonfile
  hosts: localhost
  tasks:
    - name: Display the JSON file content
      shell: cat ../terraform/terraform.tfstate
      register: result

    - name: save the Json data to a Variable as a Fact
      set_fact:
        jsondata: "{{ result.stdout | from_json }}"

    - name: get bastion public ip
      set_fact:
        bastion_public_ip: "{{ jsondata | json_query(jmesquery) }}"
      vars:
        jmesquery: "outputs.bastion_public_ip.value"

    - name: Debug the values
      debug:
        msg: "bastion_public_ip --------->> {{ bastion_public_ip }}"